apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 86.0.0
    helm:
      releaseName: monitoring
      valuesObject:
        alertmanager:
          enabled: false
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          tls:
            enabled: false
          tolerations:
            - key: dedicated
              operator: Equal
              value: gpu-workload
              effect: NoSchedule
        prometheus:
          service:
            type: ClusterIP
          prometheusSpec:
            retention: 2h
            retentionSize: 512MB
            tolerations:
              - key: dedicated
                operator: Equal
                value: gpu-workload
                effect: NoSchedule
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 768Mi
        grafana:
          adminPassword: lesson9-grafana-demo
          tolerations:
            - key: dedicated
              operator: Equal
              value: gpu-workload
              effect: NoSchedule
          service:
            type: ClusterIP
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
        kube-state-metrics:
          tolerations:
            - key: dedicated
              operator: Equal
              value: gpu-workload
              effect: NoSchedule
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 192Mi
        nodeExporter:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
